name: deploy-dev
on:
  push:
    branches:
      [
        'main',
        'bug/**',
        'feature/**',
        'issues/**',
        'githubPage/**',
        'renovate/**',
      ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # yarnコマンドを指定しています

      - id: prettier-check
        run: yarn format:check
        shell: bash
