name: renovate
on:
  workflow_dispatch:
    schedule:
      # JST everyday action on 12:00
      - cron: '0 3 * * *'

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
